version: '3'
services:
    php-apache:
        container_name: vz-old.hrabova.info 
        image: radys/php-apache:7.4
        restart: always
        ports:
            - 127.0.0.1:8078:80
        volumes:
            - ./volumes/app:/var/www/html
            - /etc/localtime:/etc/localtime:ro
